// <auto-generated />
using System;
using HW14.MovieActors.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW14.MovieActors.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW14.MovieActors.Data.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1970, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Актор, сценарист, режисер, продюсер",
                            FirstName = "Ітан",
                            LastName = "Гоук"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1969, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Актриса, продюсер, режисер",
                            FirstName = "Дженніфер",
                            LastName = "Еністон"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1948, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Актор",
                            FirstName = "Жан",
                            LastName = "Рено"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1938, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Актор",
                            FirstName = "Крістофер",
                            LastName = "Ллойд"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1961, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Актор",
                            FirstName = "Майкл",
                            LastName = "Дж. Фокс"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1979, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Актриса",
                            FirstName = "Дженніфер",
                            LastName = "Моррісон"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1976, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Актриса",
                            FirstName = "Дайан",
                            LastName = "Крюгер"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
