// <auto-generated />
using System;
using HW05.MovieManager.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW05.MovieManager.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW05.MovieManager.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            ReleaseDate = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Приборкувачка драконів"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            ReleaseDate = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Повстання Штатів"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            ReleaseDate = new DateTime(2024, 4, 12, 10, 47, 4, 787, DateTimeKind.Local).AddTicks(3904),
                            Title = "Панда Кунг-Фу 4"
                        });
                });

            modelBuilder.Entity("HW05.MovieManager.Domain.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            RoomName = "Зал 4",
                            StartAt = new DateTime(2024, 4, 11, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            RoomName = "Зал 4",
                            StartAt = new DateTime(2024, 4, 11, 16, 40, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 2,
                            RoomName = "Зал 1",
                            StartAt = new DateTime(2024, 4, 11, 14, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 2,
                            RoomName = "Зал 2",
                            StartAt = new DateTime(2024, 4, 11, 15, 50, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 2,
                            RoomName = "Зал 1",
                            StartAt = new DateTime(2024, 4, 11, 17, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 2,
                            RoomName = "Зал 1",
                            StartAt = new DateTime(2024, 4, 11, 19, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 2,
                            RoomName = "Зал 2",
                            StartAt = new DateTime(2024, 4, 11, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 3,
                            RoomName = "Зал 7",
                            StartAt = new DateTime(2024, 4, 11, 14, 20, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 3,
                            RoomName = "Зал 7",
                            StartAt = new DateTime(2024, 4, 11, 16, 20, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HW05.MovieManager.Domain.Entities.Session", b =>
                {
                    b.HasOne("HW05.MovieManager.Domain.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
