###
# ███ Insert order ████████████████████████████████████████████████████████████
###

POST {{Store_HostAddress}}/Order
content-type: application/json

{
    "customerId" : 13,
    "notes": "Для роботи (1)"
}

###

POST {{Store_HostAddress}}/Order
content-type: application/json

{
    "customerId" : 2,
    "notes": "Подарунки на день народження"
}

###
# ███ Update order ████████████████████████████████████████████████████████████
###

PUT {{Store_HostAddress}}/Order/13
content-type: application/json

{
    "notes": "Для роботи (2)"
}

###

POST {{Store_HostAddress}}/Order/13
content-type: application/json

{
    "notes": "Для розваг (3)"
}

###
# ███ Delete Order ████████████████████████████████████████████████████████████
###

DELETE {{Store_HostAddress}}/Order/1
content-type: application/json#

###
# ███ Get Order ███████████████████████████████████████████████████████████████
###

GET {{Store_HostAddress}}/Order/1
content-type: application/json

###
# ███ Get orders ██████████████████████████████████████████████████████████████
###

GET {{Store_HostAddress}}/Order
content-type: application/json









###
# ███ Insert OrderLine of Order ███████████████████████████████████████████████
###

POST {{Store_HostAddress}}/Order/1/OrderLine
content-type: application/json

{
    "productId": 4,
    "productAmount": 2,
    "notes": "Чи підійде, необхідна консультація спеціаліста!"
}

###
# ███ Update OrderLine of Order ███████████████████████████████████████████████
###

PUT {{Store_HostAddress}}/Order/1/OrderLine/4
content-type: application/json

{
  "productAmount": 2,
  "notes": "Чи підійде мені цей продукт? Необхідна консультація спеціаліста!"
}

###
# ███ Delete OrderLine of Order ███████████████████████████████████████████████
###

DELETE {{Store_HostAddress}}/Order/13/OrderLine/1

content-type: application/json#


###
# ███ Delete OrderLines of Order ██████████████████████████████████████████████
###

DELETE {{Store_HostAddress}}/Order/1/OrderLine
content-type: application/json#

###
# ███ Get OrderLine of Order █████████████████████████████████████████████████
###

GET {{Store_HostAddress}}/Order/1/OrderLine/4
content-type: application/json

###
# ███ Get OrderLines of Order █████████████████████████████████████████████████
###

GET {{Store_HostAddress}}/Order/1/OrderLine
content-type: application/json