###
# ███ Movie create ██████████████████████████████████████████████████
###

POST {{AppHostAddress}}/Movie
content-type: application/json
api-version: 1.0

{
    "title": "Дюна: Частина друга",
    "description": "Фантастично - пригодницький бойовик «Дюна: Частина друга» є продовженням фільму, що вийшов на екрани в 2021 році. В основу сюжету покладено однойменний роман Френка Герберта.",
    "releaseDate": "2024-04-12T07:36:23.196Z"
}


